# Generated by Django 3.0.5 on 2020-05-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_home_heading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='education',
        ),
    ]
