# Generated by Django 3.0.5 on 2020-05-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200529_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='contactdetails',
            field=models.TextField(blank=True),
        ),
    ]
